server: 
  port: 9003
  servlet:
    context-path: /qa
spring: 
  application:  
    name: microservice-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.155:3306/tensquare_qa?characterEncoding=UTF8
    username: root
    password: 12345
  jpa: 
    database: MySQL
    show-sql: true
