server: 
  port: 9003
  servlet:
    context-path: /
spring: 
  application:  
    name: microservice-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.238.166:3306/tensquare_qa?characterEncoding=UTF8
    username: root
    password: 12345
  jpa: 
    database: MySQL
    show-sql: true
eureka:
  instance:
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
