server: 
  port: 9010
spring: 
  application:  
    name: microservice_user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.238.166:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 12345
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.238.166
    port: 6379
  rabbitmq:
    host: 192.168.238.166
    port: 5672
    username: guest
    password: guest
#添加自定义properties配置
jwt:
  config:
    key: yanzhi
    ttl: 3600000
