server:
  port: 9009
  servlet:
    context-path: /
spring:
  application:
    name: microservice-sendmessage
  devtools:
    livereload:
      enabled: true
  rabbitmq:
    host: 192.168.238.166
    port: 5672
    username: guest
    password: guest